### ISSUE TITLE
How do we handle pagination?

### ISSUE THREAD

**Issue by spenceryu** [Guptacos/spotifython#16]
For each search result type, the contents (album object, artist object, etc.) are stored in a [paging object](https://developer.spotify.com/documentation/web-api/reference/object-model/#paging-object). The question arises with how we want to handle interacting with the paging.
- Since we can have a search result object, should we be allowing the user to do: 
    -`searchResult.artists()` to get the current page of artist results, and completely hide the other page results from the user? This feels completely wrong because we are introducing arbitrary restrictions on the API.
    -`searchResult.artists()` to get the artists pagination object,`searchResult.artists().curr_page()` to get the current page, and other methods (`next_page()`, etc.) to modify the page of the pagination object?

**Comment by Guptacos** [comment]
I updated the name of this issue to reflect _all_ pagination, instead of just search's pagination, as I think we should be consistent throughout the api

**Comment by Guptacos** [comment]
As per our discussion yesterday, here is how we plan to move forward with pagination:

- For any function that doesn't return everything, but paginates the results, we should hide this from the user as much as possible.
- Users should provide a "limit" parameter to us, and we take care of paginating and returning that many to them.
- Default "limit" value: for functions with a reasonable limit, we provide it as a default. Otherwise the user must provide a limit.

**Comment by spenceryu** [comment]
Exception: search can handle at most 2000 elements (but this would take 40 API calls). For this case we do not want to provide a default limit value to ensure that the API is performant.

**Comment by spenceryu** [comment]
Resolved - use a user specified search limit.
